[Settings]
# 接口最小速率（单位M/s），需要开启 open_filter_speed 才能生效 | Minimum rate of the interface (unit M/s), need to enable open_filter_speed to take effect
min_speed = 0.5
# 开启代理，自动获取免费可用代理，若更新无数据可开启此模式; 可选值: True, False | Enable proxy, automatically obtain free available proxy, If there are no updates, this mode can be enabled; Optional values: True, False
open_proxy = True
# 强制认为当前网络支持IPv6，跳过检测 | Force to consider that the current network supports IPv6, skip detection
ipv6_support = True
# 接口最小分辨率，需要开启 open_filter_resolution 才能生效 | Minimum resolution of the interface, need to enable open_filter_resolution to take effect
min_resolution = 1280×720
